INSERT INTO role (name) values ('Backend Developer');
INSERT INTO role (name) values ('Team leader');
INSERT INTO role (name) values ('Frontend Developer');
INSERT INTO role (name) values ('Architect');
INSERT INTO role (name) values ('Project Manager');
INSERT INTO role (name) values ('Backend Developer');
INSERT INTO role (name) values ('Team leader');
INSERT INTO role (name) values ('Frontend Developer');
INSERT INTO role (name) values ('Architect');
INSERT INTO role (name) values ('Project Manager');
INSERT INTO role (name) values ('Frontend Developer');
INSERT INTO role (name) values ('Vitor');
INSERT INTO role (name) values ('Josue');
INSERT INTO role (name) values ('Frank');
INSERT INTO role (name) values ('Gerson');
