INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (1, 'Beginner', 0, 20, 'https://roadmap.sh/ai/backend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (1, 'Advanced Beginner', 21, 40, 'https://roadmap.sh/ai/from-beginner-to-advanced-beginner-backend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (1, 'Intermediate', 41, 60, 'https://roadmap.sh/ai/from-advanced-beginner-to-intermediate-backend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (1, 'Proficient', 61, 80, 'https://roadmap.sh/ai/from-intermediate-to-proficient-backend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (1, 'Expert', 81, 100, 'https://roadmap.sh/ai/from-proficient-to-expert-backend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (2, 'Junior', 0, 30, 'https://roadmap.sh/team-leader');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (2, 'Advanced Beginner', 31, 50, 'https://roadmap.sh/ai/from-junior-to-advanced-beginner-team-leader');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (2, 'Intermediate', 51, 70, 'https://roadmap.sh/ai/from-advanced-beginner-to-intermediate-team-leader');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (2, 'Proficient', 71, 90, 'https://roadmap.sh/ai/from-intermediate-to-proficient-team-leader');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (2, 'Expert', 91, 100, 'https://roadmap.sh/ai/from-proficient-to-expert-team-leader');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (3, 'Beginner', 0, 25, 'https://roadmap.sh/r/frontend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (3, 'Advanced Beginner', 26, 45, 'https://roadmap.sh/ai/from-beginner-to-advanced-beginner-frontend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (3, 'Competent', 46, 65, 'https://roadmap.sh/ai/from-advanced-beginner-to-competent-frontend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (3, 'Proficient', 66, 85, 'https://roadmap.sh/ai/from-competent-to-proficient-frontend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (3, 'Expert', 86, 100, 'https://roadmap.sh/ai/from-proficient-to-expert-frontend-developer');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (4, 'Beginner', 0, 40, 'https://roadmap.sh/architect');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (4, 'Mid Level', 41, 60, 'https://roadmap.sh/ai/from-beginner-to-mid-level-architect');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (4, 'Competent', 61, 80, 'https://roadmap.sh/ai/from-mid-level-to-competent-architect');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (4, 'Proficient', 81, 90, 'https://roadmap.sh/ai/from-competent-to-proficient-architect');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (4, 'Expert', 91, 100, 'https://roadmap.sh/ai/from-proficient-to-expert-programming-architect');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (5, 'Beginner', 0, 10, 'https://roadmap.sh/project-manager');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (5, 'Advanced Beginner', 11, 30, 'https://roadmap.sh/ai/from-beginner-to-advanced-beginner-project-manager');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (5, 'Intermediate', 31, 50, 'https://roadmap.sh/ai/from-advanced-beginner-to-intermediate-project-manager');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (5, 'Proficient', 51, 70, 'https://roadmap.sh/ai/from-intermediate-to-proficient-project-manager');
INSERT INTO levels (role_id, name, min_coefficient, max_coefficient, link) VALUES (5, 'Expert', 71, 100, 'https://roadmap.sh/ai/from-proficient-to-expert-project-manager');

